name: Deploy Pages
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin
      
      - name: Create data directories
        run: |
          mkdir -p docs/data
          mkdir -p docs/reports
          mkdir -p docs/reports/mt-framework
          mkdir -p docs/reports/re-engine
          mkdir -p docs/reports/redengine4
          mkdir -p docs/reports/unreal-engine
          mkdir -p docs/reports/unity-engine
      
      - name: Run AI analysis
        run: |
          python scripts/ai-analysis.py --output-dir docs/data
      
      - name: Generate GitHub Pages content
        run: |
          python scripts/generate-github-pages.py --source-dir . --output-dir docs
      
      - name: Build documentation
        run: |
          mkdocs build --site-dir docs/_site
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
